### ISSUE TITLE
Does not support php7

### ISSUE THREAD

**Issue by harshapower** [baneeishaque/e-learn_web#1]
After importing two databases following errors are appearing 

Fatal error: Uncaught Error: Call to undefined function mysql_select_db() in C:\xampp\htdocs\e-learn_web-master\admin\dbcon.php:2 Stack trace: #0 C:\xampp\htdocs\e-learn_web-master\header.php(30): include() #1 C:\xampp\htdocs\e-learn_web-master\index.php(2): include('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\e-learn_web-master\admin\dbcon.php on line 2

**Comment by baneeishaque** [comment]
use php5, php7 doesn't contain php_mysql library.
I think you are using xampp - use a version of xampp which comes with php5 instead of php7.
